### ISSUE TITLE
similar idea for a boxcox package 

### ISSUE THREAD

**Issue by lindemann09** [palday/BoxCox.jl#2]
I accidentally noticed that you created a BoxCox.jl repository. Great! Such a package is indeed needed. Unfortunately, [BoxCoxTrans.jl](https://github.com/tk3369/BoxCoxTrans.jl) seems not to be any more under development and it does not really fit in its current form to the JuliaStats environment. It can also not handle models and their residuals.  

I had once a pretty similar idea for a Power transformation package and pushed today the highly preliminary package code. [BoxCoxTransformations.jl](https://github.com/lindemann09/BoxCoxTransformations.jl) Might be interesting. 

I suggest to have more general "PowerTransformations.jl" package that gives also space for other kind of transformations (e.g. Yeo-Johnson). 

Greetings,
Oliver

**Comment by palday** [comment]
Yeo-Johnson and Bickel-Doksum are already on my radar for this package. :smile: 

I've started the registration process, so hopefully the first official release will be out in a few days. :tada: This package was explicitly defined to match a lot of the features of R's `MASS:boxcox`, even using the same scaling to get similar results for the log likelihood profile.
